# Generated by Django 2.2.5 on 2019-10-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=255, unique=True)),
                ('categoryImagePath', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Order date')),
                ('order_time', models.TimeField(auto_now_add=True, verbose_name='Order time')),
                ('address', models.CharField(max_length=500)),
                ('phone_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_tech.RegUser')),
            ],
        ),
        migrations.CreateModel(
            name='CategorizedProducts',
            fields=[
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_price', models.IntegerField()),
                ('product_rating', models.FloatField()),
                ('product_descp', models.CharField(max_length=255)),
                ('product_imagepath', models.CharField(default='media/images/clothing.png', max_length=255)),
                ('under_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_tech.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Addresses2',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('house_no', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=30)),
                ('landmark', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('phone_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_tech.RegUser')),
            ],
        ),
    ]
