# Generated by Django 2.2.5 on 2019-10-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='address',
            field=models.CharField(default='Roorkee', max_length=500),
        ),
        migrations.AddField(
            model_name='vendors',
            name='name',
            field=models.CharField(default='Hemil', max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delboy_type',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary')], default='S', max_length=50),
        ),
    ]
