# Generated by Django 2.2.1 on 2019-10-06 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='products',
        ),
        migrations.CreateModel(
            name='Vendor_Products',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('vendor_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_tech.Vendors')),
            ],
        ),
    ]
