# Generated by Django 2.2.5 on 2019-10-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_orders',
            name='cust_lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscribed_orders',
            name='cust_long',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
