# Generated by Django 2.2.5 on 2019-10-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delboy_type',
            field=models.CharField(blank=True, choices=[('P', 'Primary'), ('S', 'Secondary')], default='S', max_length=50, null=True),
        ),
    ]
