# Generated by Django 2.2.5 on 2019-10-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_products',
            name='product_id',
            field=models.CharField(default='001', max_length=255),
        ),
    ]
