# Generated by Django 2.2.5 on 2019-10-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_boys',
            name='city',
            field=models.CharField(default='Roorkee', max_length=255),
            preserve_default=False,
        ),
    ]
