# Generated by Django 2.2.1 on 2019-10-01 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('phone_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vendor_lat', models.IntegerField()),
                ('vendor_long', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Products',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('vendor_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_tech.Vendors')),
            ],
        ),
    ]
