# Generated by Django 2.2.5 on 2019-10-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cells',
            fields=[
                ('cell_no', models.IntegerField(primary_key=True, serialize=False)),
                ('cell_lat', models.FloatField()),
                ('cell_long', models.FloatField()),
                ('no_vendor', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='vendors',
            name='cell_no',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
