# Generated by Django 2.2.5 on 2019-10-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0002_auto_20191009_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Boys',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=20)),
                ('total_no_orders', models.IntegerField()),
                ('current_no_orders', models.IntegerField()),
                ('busy', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='phone_no',
            new_name='customer_phone',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('D', 'Delivered'), ('A', 'Active')], default='A', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='vendor_phone',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendors',
            name='busy',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendors',
            name='current_no_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendors',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=20),
        ),
        migrations.AddField(
            model_name='vendors',
            name='total_no_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Serving_Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=500)),
                ('phone_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_tech.Vendors')),
            ],
        ),
        migrations.CreateModel(
            name='Deliverying_Boys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=500)),
                ('phone_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_tech.Delivery_Boys')),
                ('vendor_phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_tech.Vendors')),
            ],
        ),
    ]
