# Generated by Django 2.2.5 on 2019-10-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0002_auto_20191022_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='vendor_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
