# Generated by Django 2.2.1 on 2019-10-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0002_vendor_products_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='vendor_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_long',
            field=models.FloatField(),
        ),
    ]
