# Generated by Django 2.2.5 on 2019-10-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0002_delivery_boys_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='cells',
            name='city',
            field=models.CharField(default='Roorkee', max_length=255),
        ),
    ]
