# Generated by Django 2.2.5 on 2019-10-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0002_auto_20191023_2043'),
        ('base_tech', '0002_auto_20191024_1116'),
    ]

    operations = [
    ]
