# Generated by Django 2.2.5 on 2019-10-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0003_auto_20191001_2111'),
        ('base_tech', '0002_auto_20191003_1252'),
    ]

    operations = [
    ]
