# Generated by Django 2.2.5 on 2019-10-12 07:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0003_auto_20191010_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_boy_phone',
            field=models.ForeignKey(default=9876, on_delete=django.db.models.deletion.PROTECT, to='base_tech.Delivery_Boys'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_tech.CategorizedProducts'),
        ),
        migrations.CreateModel(
            name='Subscribed_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorder_id', models.CharField(default=uuid.uuid4, max_length=100)),
                ('delivery_time', models.TimeField(verbose_name='Delivery time')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('A', 'Active'), ('E', 'Expired')], default='A', max_length=20)),
                ('customer_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_tech.RegUser')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_tech.CategorizedProducts')),
                ('vendor_phone', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='base_tech.Vendors')),
            ],
        ),
    ]
