# Generated by Django 2.2.1 on 2019-09-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0003_auto_20190919_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_category', models.IntegerField()),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('product_id', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_rating', models.FloatField()),
                ('product_descp', models.CharField(max_length=255)),
            ],
        ),
    ]
