# Generated by Django 2.2.5 on 2019-10-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0003_auto_20191023_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product_name',
        ),
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.PROTECT, to='base_tech.CategorizedProducts'),
            preserve_default=False,
        ),
    ]
