# Generated by Django 2.2.1 on 2019-09-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0004_categorizedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorizedproducts',
            name='product_imagepath',
            field=models.CharField(default='media/images/clothing.png', max_length=255),
        ),
    ]
