# Generated by Django 2.2.5 on 2019-10-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0004_auto_20191015_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_boys',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
