# Generated by Django 2.2.5 on 2019-10-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0005_auto_20191015_1816'),
        ('base_tech', '0002_auto_20191016_2049'),
    ]

    operations = [
    ]
