# Generated by Django 2.2.5 on 2019-10-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0005_auto_20191013_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_boy_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base_tech.Delivery_Boys'),
        ),
    ]
