# Generated by Django 2.2.5 on 2019-10-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0006_merge_20191021_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='product_id',
            new_name='product_name',
        ),
    ]
