# Generated by Django 2.2.5 on 2019-10-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0006_auto_20191013_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cust_lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='cust_long',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_boys',
            name='busy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='vendor_phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subscribed_orders',
            name='vendor_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base_tech.Vendors'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='busy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
