# Generated by Django 2.2.5 on 2019-10-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0007_auto_20191021_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product_name',
            field=models.CharField(max_length=500),
        ),
    ]
