# Generated by Django 2.2.5 on 2019-10-22 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0007_auto_20191021_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_products',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_tech.CategorizedProducts'),
        ),
    ]
