# Generated by Django 2.2.5 on 2019-10-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0008_auto_20191021_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='vendor_phone',
        ),
    ]
