# Generated by Django 2.2.5 on 2019-10-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0008_auto_20191022_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_products',
            name='serial',
        ),
        migrations.AddField(
            model_name='vendor_products',
            name='id',
            field=models.AutoField(auto_created=True, default=23, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
