# Generated by Django 2.2.5 on 2019-10-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0009_remove_orders_vendor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='vendor_phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
