# Generated by Django 2.2.5 on 2019-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0009_auto_20191022_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_boys',
            name='del_boy_id',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendors',
            name='vendor_id',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
    ]
