# Generated by Django 2.2.5 on 2019-10-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_tech', '0010_orders_vendor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delboy_type',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary')], default='S', max_length=50),
        ),
    ]
